name: Run Tests

on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
        
  deploy:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Connect to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
           cd /home/farm
           git pull origin main
           sudo systemctl restart nginx 
